"""Assemble isolated operand examples; never execute the generated bytes."""
from pathlib import Path
import shutil
import subprocess
import tempfile

cases = [
    ("xor ax, bx", True),
    ("xor ax, ds", False),
    ("mov bx, ds\nxor ax, bx", True),
    ("xor ax, bl", False),
    ("xor ax, [si]", True),
    ("xor word [si], 1", True),
    ("xor [si], [di]", False),
    ("mov ds, ax", True),
    ("mov ds, 0", False),
    ("mov byte [si], 1", True),
    ("mov word [si], 1", True),
    ("mov al, [si]", True),
    ("mov al, [bx + si]", True),
    ("mov al, [ax]", False),
]

nasm = shutil.which("nasm")
if not nasm:
    raise SystemExit("Install NASM or put it on PATH before running this check.")
with tempfile.TemporaryDirectory(prefix="assembly-lab-operands-") as directory:
    root = Path(directory)
    for instruction, expected in cases:
        source = root / "example.asm"
        source.write_text("bits 16\n" + instruction + "\n")
        result = subprocess.run(
            [nasm, "-f", "bin", "-o", str(root / "example.bin"), str(source)],
            capture_output=True, text=True,
        )
        accepted = result.returncode == 0
        if accepted != expected:
            raise SystemExit(f"Unexpected result for {instruction!r}: {result.stderr}")
        print(f"{'Accepted' if accepted else 'Rejected'}: {instruction.replace(chr(10), ' / ')}")
print(f"All {len(cases)} operand expectations verified; no machine code executed.")
